"""Initial migration

Revision ID: 630a3d865f96
Revises: 
Create Date: 2025-04-01 18:43:45.735463

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '630a3d865f96'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ListaProductos')
    op.add_column('Categoria', sa.Column('Nombre', sa.String(length=100), nullable=False))
    op.drop_column('Categoria', 'NombreCategoria')
    op.alter_column('Lista', 'IdUsuario',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('Lista', 'IdProveedor',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('lista_proveedor_id_key', 'Lista', type_='unique')
    op.drop_constraint('lista_usuario_id_key', 'Lista', type_='unique')
    op.alter_column('Producto', 'IdCategoria',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('Producto', 'IdUnidadMedida',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('producto_categoria_id_key', 'Producto', type_='unique')
    op.drop_constraint('producto_unidad_medida_id_key', 'Producto', type_='unique')
    op.alter_column('Proveedor', 'IdTipoProveedor',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('proveedor_tipo_proveedor_id_key', 'Proveedor', type_='unique')
    op.add_column('TipoProveedor', sa.Column('Nombre', sa.String(length=100), nullable=False))
    op.drop_column('TipoProveedor', 'NombreTipoProveedor')
    op.add_column('TipoUsuario', sa.Column('Nombre', sa.String(length=100), nullable=False))
    op.drop_column('TipoUsuario', 'NombreTipoUsuario')
    op.add_column('UnidadMedida', sa.Column('Nombre', sa.String(length=100), nullable=False))
    op.drop_column('UnidadMedida', 'NombreUnidadMedida')
    op.add_column('Usuario', sa.Column('DireccionPreferencial', sa.String(length=100), nullable=True))
    op.alter_column('Usuario', 'IdTipoUsuario',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('Usuario', 'NombreUsuario',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.drop_constraint('usuario_tipo_usuario_id_key', 'Usuario', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('usuario_tipo_usuario_id_key', 'Usuario', ['IdTipoUsuario'])
    op.alter_column('Usuario', 'NombreUsuario',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('Usuario', 'IdTipoUsuario',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('Usuario', 'DireccionPreferencial')
    op.add_column('UnidadMedida', sa.Column('NombreUnidadMedida', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_column('UnidadMedida', 'Nombre')
    op.add_column('TipoUsuario', sa.Column('NombreTipoUsuario', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_column('TipoUsuario', 'Nombre')
    op.add_column('TipoProveedor', sa.Column('NombreTipoProveedor', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_column('TipoProveedor', 'Nombre')
    op.create_unique_constraint('proveedor_tipo_proveedor_id_key', 'Proveedor', ['IdTipoProveedor'])
    op.alter_column('Proveedor', 'IdTipoProveedor',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_unique_constraint('producto_unidad_medida_id_key', 'Producto', ['IdUnidadMedida'])
    op.create_unique_constraint('producto_categoria_id_key', 'Producto', ['IdCategoria'])
    op.alter_column('Producto', 'IdUnidadMedida',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('Producto', 'IdCategoria',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_unique_constraint('lista_usuario_id_key', 'Lista', ['IdUsuario'])
    op.create_unique_constraint('lista_proveedor_id_key', 'Lista', ['IdProveedor'])
    op.alter_column('Lista', 'IdProveedor',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('Lista', 'IdUsuario',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('Categoria', sa.Column('NombreCategoria', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_column('Categoria', 'Nombre')
    op.create_table('ListaProductos',
    sa.Column('IdLista', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('IdProducto', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('PrecioActual', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('Cantidad', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['IdLista'], ['Lista.IdLista'], name='lista_productos_lista_id_fkey'),
    sa.ForeignKeyConstraint(['IdProducto'], ['Producto.IdProducto'], name='lista_productos_producto_id_fkey'),
    sa.PrimaryKeyConstraint('IdLista', 'IdProducto', name='lista_productos_pkey')
    )
    # ### end Alembic commands ###
